apiVersion: apps/v1
kind: Deployment
metadata:
  name: "innovate-accounts"
  labels:
    chart: 'innovate-accounts-1.0.0'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "innovate-accounts"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: "innovate-accounts"
    spec:
      imagePullSecrets:
        - name: "gcr"
      containers:
      - name: "innovate-accounts"
        image: "eu.gcr.io/gcr-public-193675/innovate-digital-bank-demo-accounts:latest"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3400
          initialDelaySeconds: 3000
          periodSeconds: 1000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: PORT
            value : 3400
          - name: BASE_PATH
            value : "innovate-accounts"
          - name: MONGO_URL
            value : "mongodb://mongouser:secret-pass@some-cluster-end-point:27017/?ssl=true"
