kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: aks-anhots-01
  labels:
    provider: azure
    location: london
    region: uksouth
    env: demo
    envtype: nonprod
    priority: one
