# cluster selectros as per:
# https://cloud.google.com/anthos-config-management/docs/how-to/clusterselectors
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
    name: priority-one
spec:
    selector:
      matchLabels:
          priority: 1
